In [ ]:
Arithmetic Operation

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2=  np.array([6,7,8,9,10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [16]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
Broadcasting 

In [9]:
l = [10,20,20,30]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 30, 40])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
Deep and shallow Copy 

SyntaxError: invalid syntax (2641093570.py, line 1)

In [14]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice= arr[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [16]:
arr[4:6]*10

array([50, 60])

In [17]:
Matrix Operation

SyntaxError: invalid syntax (3378453542.py, line 1)

In [18]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
B

array([[5, 6],
       [7, 8]])

In [21]:
A @ B

array([[19, 22],
       [43, 50]])

In [22]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
Advanced Array Manipulation

In [25]:
stacking array

SyntaxError: invalid syntax (1796003732.py, line 1)

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [28]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
Splitting Array

In [31]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [36]:
a= np.vsplit(c,2)

In [37]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
