In [1]:
print("sandeep")

sandeep


In [2]:
import numpy as np

In [4]:
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a= [1,2,3.5]
a

[1, 2, 3.5]

In [6]:
np.array(a)

array([1. , 2. , 3.5])

In [7]:
l = [[1,2,3,4],[5,6,7,8]]
l

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
np.array(l)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr= np.zeros((3,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [18]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
Random Number Generation

In [20]:
np.random.rand(10)

array([0.46833022, 0.7866139 , 0.46364844, 0.18694212, 0.48917821,
       0.99287384, 0.00687778, 0.39702271, 0.43224364, 0.57663345])

In [21]:
np.random.randn(10)

array([-0.42634123, -1.30373316, -0.85738889, -1.1204242 , -0.90532697,
        0.00578268,  0.34623576, -0.96500993, -0.2484964 ,  0.3916152 ])

In [22]:
np.random.randint(6)

5

In [24]:
np.random.randint(1,10,8)

array([4, 3, 3, 6, 1, 8, 4, 4])

In [ ]:
Array Attributes

In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [28]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.min()

np.int64(1)

In [32]:
arr.max()

np.int64(9)

In [33]:
arr.sum()

np.int64(45)

In [34]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [36]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std()

np.float64(2.581988897471611)

In [39]:
arr.argmax()

np.int64(8)

In [40]:
arr.argmin()

np.int64(0)

In [41]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])